version: "3"
services:

  minio-local:
    image: minio/minio:latest
    restart: always
    container_name: minio-local
    volumes:
      - minio_storage:/data
    env_file:
      - .env
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_ADMIN_PORT}:9001
    networks:
      - reverseproxy-nw
    command: "server /data --console-address :9001"

#   nginx:
#     image: nginx:1.19.2-alpine
#     hostname: nginx
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     ports:
#       - "8000:8000"
#       - "8001:8001"
#     networks:
#       - reverseproxy-nw
#     depends_on:
#       - minio-local

networks:
  reverseproxy-nw:
    driver: bridge

volumes:
  minio_storage: {}